# Generated by Django 6.0.3 on 2026-04-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('phone', models.CharField(max_length=12)),
                ('file', models.FileField(upload_to='uploads/')),
                ('url', models.URLField()),
                ('time', models.TimeField()),
                ('date', models.DateTimeField()),
                ('gender', models.CharField(max_length=15)),
                ('hobby', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('password', models.CharField(max_length=50)),
                ('hidden', models.CharField(max_length=100)),
            ],
        ),
    ]
