# Generated by Django 6.0.3 on 2026-04-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hidden',
        ),
    ]
