# Generated by Django 6.0.3 on 2026-04-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_student_hidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Username',
            new_name='username',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
