# Generated by Django 6.0.3 on 2026-04-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_student_image_alter_student_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='student',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
